four/basicapp/urls.py
from django.urls import re_path
from . import views

app_name = 'blah'

urlpatterns = [
    re_path(r'^register/',views.register, name='registeration'),
    re_path(r'^login/',views.ulogin, name='log'),
]

four/four/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from basicapp import views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^bapp/', include('basicapp.urls')),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^logout/$', views.ulogout, name='LO')
]

four/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UPI(models.Model):
    user = models.OneToOneField(User,models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)
    def __str__(self):
        return self.user.username

four/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UPI

class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','email','password')
class UPIform(forms.ModelForm):
    class Meta:
        model = UPI
        fields = ('portfolio_site','profile_pic')

four/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import Userform,UPIform
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def index(request):
    return render(request,'bapp/I.html')
@login_required
def ulogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def ulogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('login failed!')
            print(username,password)
            return HttpResponse('Invalid login details supplied')
    else:
        return render(request,'bapp/L.html')
def register(request):
    registered = False
    if request.method == 'POST':
        uf = Userform(data=request.POST)
        pf = UPIform(data=request.POST)
        if uf.is_valid() and pf.is_valid():
            user = uf.save()
            user.set_password(user.password)
            user.save()
            profile = pf.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(uf.errors,pf.errors)
    else:
        uf = Userform()
        pf = UPIform()
    D = {'userform':uf,'profileform':pf,'registered':registered}
    return render(request,'bapp/R.html',D)

four/templates/bapp/B.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="nav navbar-brand" href="{%url 'index'%}">Home</a></li>
          <li><a class="nav navbar-link" href="{%url 'admin:index'%}">Admin</a></li>
          <li><a class="nav navbar-link" href="{%url 'blah:registeration'%}">Registeration</a></li>
          {% if user.is_authenticated %}
          <li><a class="nav navbar-link" href="{%url 'LO'%}">Logged Out</a></li>
          {% else %}
          <li><a class="nav navbar-link" href="{%url 'blah:log'%}">Log in</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

four/templates/bapp/I.html
<!DOCTYPE html>
{% extends 'bapp/B.html' %}
{% block block_body %}
<div class="jumbotron">
  <h1>Level 5 Home</h1>
</div>
{% endblock %}

four/templates/bapp/L.html
{% extends 'bapp/B.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Please Login</h1>

      <form method="post" action="{% url 'blah:log' %}">
        {% csrf_token %}
        {# A more "HTML" way of creating the login form#}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Username">

        <label for="password"></label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">

      </form>

  </div>
</div>
{% endblock %}

four/templates/bapp/R.html
{% extends 'bapp/B.html' %}
{% load staticfiles %}
{% block block_body %}
<div class="jumbotron">
  <h1>wut</h1>
  {% if registered %}
  <p>Thank you for registering</p>
  {% else %}
  <h2>Register here</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{userform.as_p}}
    {{profileform.as_p}}
    <input type="submit" value="Register">
  </form>
  {% endif %}
</div>
{% endblock %}
<!-- {% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ userform.as_p }}
          {{ profileform.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %} -->

four/templates/bapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand"><a href="{% url 'index' %}">Brand</a></li>
          <li class="navbar-link"><a href="{% url 'admin:index' %}">Admin</a></li>
          <li class="navbar-link"><a href="{% url 'blah:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>

four/templates/bapp/index.html
<!DOCTYPE html>
{% extends "bapp/base.html" %}
  {% block body_block %}
    <h1>Welcome to Index</h1>
    {{ text|cut:'hello' }}
    {{ num|add:"99" }}
  {% endblock %}

four/templates/bapp/other.html
<!DOCTYPE html>
{% extends "bapp/base.html" %}
  {% block body_block %}
    <h1>Welcome to Other</h1>
    <h2>This is eg for inheritance</h2>
  {% endblock %}

four/templates/bapp/rurl.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Relative Url Template</title>
  </head>
  <body>
    <h1>Welcome to Relative Url Template</h1>
    <a href="{% url 'blah:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">Admin</a>
    <a href="{% url 'index' %}">to index</a>
  </body>
</html>